<?php
include'header.php';
include'menu.php';

if(isset($_GET['index'])){
    include'available.php';
}elseif(isset($_GET['current'])){
    include'current/current.php';
}
elseif(isset($_GET['review'])){
    include'review/review.php';
}
elseif(isset($_GET['completed'])){
    include'complete/complete.php';
}
elseif(isset($_GET['revision'])){
    include'revision/revision.php';
}
elseif(isset($_GET['reassign'])){
    include'reassign/reassign.php';
}
elseif(isset($_GET['mailbox'])){
    include'mail/inbox.php';
}elseif(isset($_GET['viewmail'])){
    include'mail/view-mail.php';
}
elseif(isset($_GET['compose'])){
    include'mail/compose-email.php';
}
elseif(isset($_GET['view_current'])){
    include'current/view.php';
}
elseif(isset($_GET['view_complete'])){
    include'complete/view.php';
}
elseif(isset($_GET['view_revision'])){
    include'revision/view.php';
}
elseif(isset($_GET['view_reassign'])){
    include'reassign/view.php';
}
elseif(isset($_GET['view_review'])){
    include'review/view.php';
}
else{
    include'available.php';
}
include'footerplugin.php';
?>