<?php
include'header.php';
include'menu.php';

if(isset($_GET['index'])){
    include'home.php';
}
elseif(isset($_GET['progress'])){
    include'progress/view.php';
}
elseif(isset($_GET['revision'])){
    include'revision/view.php';
}
elseif(isset($_GET['reassign'])){
    include'reassign/view.php';
}
elseif(isset($_GET['complete'])){
    include'complete/view.php';
}
elseif(isset($_GET['users'])){
    include'network/users.php';
}
elseif(isset($_GET['support'])){
    include'network/support.php';
}
elseif(isset($_GET['clients'])){
    include'network/clients.php';
}
elseif(isset($_GET['review'])){
    include'review/view.php';
}
else{
    include'home.php';
}

include'footerplugin.php';
?>