<?php
include'header.php';
include'menu.php';

if(isset($_GET['index'])){
    include'home.php';
}
elseif(isset($_GET['progress'])){
    include'progress/view.php';
}
elseif(isset($_GET['revision'])){
    include'revision/view.php';
}
elseif(isset($_GET['reassign'])){
    include'reassign/view.php';
}
elseif(isset($_GET['complete'])){
    include'complete/view.php';
}
elseif(isset($_GET['users'])){
    include'network/users.php';
}
elseif(isset($_GET['support'])){
    include'network/support.php';
}
elseif(isset($_GET['clients'])){
    include'network/clients.php';
}
elseif(isset($_GET['review'])){
    include'review/view.php';
}
elseif(isset($_GET['mail'])){
    include'mail/inbox.php';
}
elseif(isset($_GET['compose'])){
    include'mail/compose-email.php';
}
elseif(isset($_GET['viewmail'])){
    include'mail/view-mail.php';
}
elseif(isset($_GET['available'])){
    include'available/view.php';
}
elseif(isset($_GET['pay_upcoming'])){
    include'finance/pay_upcoming.php';
}
elseif(isset($_GET['pay_review'])){
    include'finance/pay_review.php';
}
elseif(isset($_GET['pay_cleared'])){
    include'finance/pay_cleared.php';
}
elseif(isset($_GET['qa'])){
    include'QA/qa.php';
}
elseif(isset($_GET['o-placement'])){
    include'placement.php';
}
else{
    include'home.php';
}

include'footerplugin.php';
?>